---
- name: Install and configure Telegraf
  hosts: all
  become: true
  vars_files:
    - vars/config.yaml

  tasks:
    - name: Download InfluxData GPG key
      get_url:
        url: https://repos.influxdata.com/influxdata-archive.key
        dest: /tmp/influxdata-archive.key
        mode: '0644'

    - name: Verify GPG key checksum
      shell: echo "943666881a1b8d9b849b74caebf02d3465d6beb716510d86a39f6c8e8dac7515  /tmp/influxdata-archive.key" | sha256sum -c -
      register: checksum_result
      failed_when: checksum_result.rc != 0
      changed_when: false

    - name: Convert GPG key to binary format
      shell: cat /tmp/influxdata-archive.key | gpg --dearmor > /etc/apt/trusted.gpg.d/influxdata-archive.gpg
      args:
        creates: /etc/apt/trusted.gpg.d/influxdata-archive.gpg

    - name: Add InfluxData repository
      apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive.gpg] https://repos.influxdata.com/debian stable main
        state: present
        filename: influxdata
        update_cache: false

    - name: Update apt cache
      apt:
        update_cache: yes
      changed_when: false

    - name: Install Telegraf
      apt:
        name: telegraf
        state: present

    - name: Configure Telegraf token in environment file
      lineinfile:
        path: /etc/default/telegraf
        create: yes
        line: 'INFLUX_TOKEN={{ influx_token }}'
        regexp: '^INFLUX_TOKEN='
        mode: '0600'
      notify: restart telegraf

    - name: Deploy Telegraf configuration
      template:
        src: templates/telegraf.conf.j2
        dest: /etc/telegraf/telegraf.conf
        owner: telegraf
        group: telegraf
        mode: '0644'
        validate: '/usr/bin/telegraf -config %s -test'  # Validates config before deploying
      notify: restart telegraf

  handlers:
    - name: restart telegraf
      service:
        name: telegraf
        state: restarted
